"""
YOLO LVIS fine-tuning configuration

All path references use the project root as base (/data/... resolved at runtime).
"""

import os
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class TrainConfig:
    """Training hyperparameters and paths"""

    # ── Model ──────────────────────────────────────────────
    model_name: str = "yolo26n.pt"
    """Base pretrained model (Ultralytics YOLO26 nano). Also supports yolo26s.pt / yolo26m.pt"""

    # ── Data paths (relative to project root) ──────────────
    lvis_root: str = "data/uploads/lvis"
    """LVIS dataset root directory"""

    output_dir: str = "data/models/lvis_finetuned"
    """Directory for saving the fine-tuned model"""

    # ── Dataset splits ─────────────────────────────────────
    train_ann: str = "annotations/lvis_v1_train.json"
    val_ann: str = "annotations/lvis_v1_val.json"
    train_img_dir: str = "train2017"
    val_img_dir: str = "val2017"

    # ── Training hyperparameters ───────────────────────────
    epochs: int = 100
    batch: int = 16
    imgsz: int = 640
    lr0: float = 0.01
    lrf: float = 0.01
    warmup_epochs: float = 3.0
    weight_decay: float = 0.0005
    cos_lr: bool = True

    # ── Data augmentation ──────────────────────────────────
    hsv_h: float = 0.015
    hsv_s: float = 0.7
    hsv_v: float = 0.4
    degrees: float = 0.0
    translate: float = 0.1
    scale: float = 0.5
    shear: float = 0.0
    perspective: float = 0.0
    flipud: float = 0.0
    fliplr: float = 0.5
    mosaic: float = 1.0
    mixup: float = 0.1

    # ── Training control ───────────────────────────────────
    device: str = ""
    """Training device: "0" for GPU 0, "cpu" for CPU, "" for auto"""
    workers: int = 8
    patience: int = 20
    """Early stopping patience (epochs)"""
    project: str = "lvis_finetune"
    name: str = "lvis_yolo26n"
    exist_ok: bool = True
    pretrained: bool = True
    optimize: str = "auto"
    save_period: int = 10
    val: bool = True
    amp: bool = True

    # ── LVIS category filtering ────────────────────────────
    min_instances: int = 10
    """Minimum instances per category to include (few-shot categories filtered out)"""
    max_categories: int = 300
    """Maximum number of LVIS categories to train on (sorted by frequency)"""

    def resolve(self, root: str) -> "TrainConfig":
        """Resolve relative paths to absolute using project root"""
        import os as _os
        def _abs(p: str) -> str:
            return p if _os.path.isabs(p) else _os.path.join(root, p)
        self.lvis_root = _abs(self.lvis_root)
        self.output_dir = _abs(self.output_dir)
        return self


@dataclass
class DataMeta:
    """LVIS dataset metadata generated by data_converter"""
    nc: int = 0
    names: List[str] = field(default_factory=list)
    yaml_path: str = ""
    train_label_dir: str = ""
    val_label_dir: str = ""


# Default config instance
DEFAULT_CONFIG = TrainConfig()
